server:
  port: 8080

minTimes: 1
maxTimes: 10
minTimesDesc: 最小次数为${minTimes}

spring:
  datasource:
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: cdh
    password: 123456
    url: jdbc:mysql://10.101.130.218:3306/dw_jpark?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug